---
kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          livenessProbe:
            exec:
              command:
              - sh
              - /check.sh
            initialDelaySeconds: 10
            periodSeconds: 5
  selector:
    matchLabels:
      app: phpmyadmin 